export const portSummaryModel = [
  'total_loan',
  'active_account',
  'average_loan_size',
  'average_int',
  'total_size',
  'multi_loan',
  'total_payment',
  'new_loan',
  'new_size',
  'average_newloan_size',
  'average_new_int',
  'mtd_loan',
  'mtd_rate',
  'delinquent_loan',
  'npl_loan',
  'delinquent_rate1_3',
  'delinquent_rate1_6',
  'npl_rate',
  'recovery_rate',
  'ref',
]

export const portSummaryOption = [
  'INT',
  'INT',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'INT',
  'DOUBLE',
  'INT',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'INT',
  'DOUBLE',
  'INT',
  'INT',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'VARCHAR(20) UNIQUE'
]