export const portTotalModel = [
  'total_loan',
  'total_app',
  'multi_loan',
  'new_loan',
  'mtd_loan',
  'delinquent_loan',
  'npl_loan',
  'non_starter_loan',
  'total_size',
  'size1_6',
  'total_payment',
  'delinquent_amount',
  'average_loan_size',
  'average_int',
  'growth_rate',
  'debt_rate',
  'delinquent_rate1_6',
  'delinquent_rate1_3',
  'npl_rate',
  'recovery_rate',
  'date',
]

export const portTotalOption = [
  'INT',
  'INT',
  'INT',
  'INT',
  'INT',
  'INT',
  'INT',
  'INT',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'DOUBLE',
  'VARCHAR(6) UNIQUE'
]